services:
  restaurant-db:
    image: postgres:15-alpine
    container_name: restaurant-db
    ports:
      - "5232:5432" # Хост:Контейнер
    volumes:
      - restaurant-postgres-data:/var/lib/postgresql/data
    env_file:
      - .env.dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U restaurant_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      target: dev
    env_file:
      - .env.dev
    depends_on:
      restaurant-db:
        condition: service_healthy
    command: sleep infinity

volumes:
  restaurant-postgres-data: