services:
  psql:
    image: postgres:15-alpine
    container_name: psql
    volumes:
      - psql-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U restaurant_user -d restaurant_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    depends_on:
      psql:
        condition: service_healthy

volumes:
  psql-data: